### ISSUE TITLE
it can't work when all the points are  on the plane 

### ISSUE THREAD

**Issue by FLOWERCLOUD** [OskarSigvardsson/unity-quickhull#1]
generate convex hull fail. I run the code on a plane mesh.

**Comment by SlimeQ** [comment]
What's more, this algorithm doesn't work if the model has **any** complex planes on its surface. For example, I'm attempting to generate a hull for these datapoints:

![image](https://user-images.githubusercontent.com/3934698/66523505-1c3daa80-eabe-11e9-91f8-8d10fa22e913.png)

The result is just a tiny line constructed from 4 triangles which consist of the first 12 verts. I'm looking into why this may be happening but it's not very clear to me at this point.

**Comment by OskarSigvardsson** [comment]
@SlimeQ I'm not working actively on this anymore (as you can probably tell), it was always a hobby thing and life-stuff came in the way.

It's not too surprising that it doesn't work if all points are coplanar (since it's sort-of a degenerate case anyway), but I am a bit surprised it doesn't work on that cube. Do you have a more minimal example? If it breaks if there are *any* coplanar points, does it also break if you have a tetrahedron of four points + a single point on one of the faces? (EDIT: or a cube with 8 regular vertices and one in the center of one of the faces?)

If you can produce a minimal test case like that, I can take a look and see if I can make sense of it.

**Comment by SlimeQ** [comment]
Working (corners only): 
![image](https://user-images.githubusercontent.com/3934698/66579629-1c37bc00-eb4b-11e9-9f2e-630aad5a37d8.png)

Still working (one in the center of this plane):
![image](https://user-images.githubusercontent.com/3934698/66579760-52753b80-eb4b-11e9-9b13-0908e2ce308a.png)

Still working...
![image](https://user-images.githubusercontent.com/3934698/66579895-881a2480-eb4b-11e9-952e-7ab3d1083dd9.png)

Still working...
![image](https://user-images.githubusercontent.com/3934698/66579975-a5e78980-eb4b-11e9-9715-e1be5fc12216.png)

...
![image](https://user-images.githubusercontent.com/3934698/66580133-e5ae7100-eb4b-11e9-8245-05475adfefc0.png)

I guess maybe it's not that. I believe in the broken case, the first several verts are all in a line? This is the actual mesh that is generated (just those 4 points linked together):

![image](https://user-images.githubusercontent.com/3934698/66581022-5a35df80-eb4d-11e9-9b90-769441bd3ff8.png)

Here's the triangles: 
![image](https://user-images.githubusercontent.com/3934698/66580573-9caaec80-eb4c-11e9-8e9f-51f0b578c1ec.png)

And the relevant points:
![image](https://user-images.githubusercontent.com/3934698/66580801-f8757580-eb4c-11e9-9841-f727bef41538.png)

There's 187 points total, 12 through 187 get skipped completely.

Removed a chunk from the bottom, including the offending 12 points:
![image](https://user-images.githubusercontent.com/3934698/66581369-fb249a80-eb4d-11e9-907f-f835851de61c.png)
Technically works, though the resulting mesh has some issues (corners omitted, entire green vertical edge omitted)

Hopefully that gives you some hint, there appears to be a pretty crucial error happening somewhere in there. For reference, this cube has 10 points in between each corner, meaning 12 per edge. 

I think maybe the order of the verts has something to do with this?

**Comment by OskarSigvardsson** [comment]
Hmm. That is very weird, yeah. 

I'll try and find some time to work on this this weekend to check this out. If you can reduce the set of points as much as possible I'd appreciate it. I'll check out the set of points you showed in the other issue, but for this kinds of stuff, it's REALLY helpful if you can get it down to a minimal case. 

Again though: NO PROMISES. This is what you get when you use code from random github pages 🙂

**Comment by SlimeQ** [comment]
I was able to get this library working in unity fairly painlessly (https://github.com/DesignEngrLab/MIConvexHull) and it does not have this issue so by all means don't stress about fixing this one. Thanks for the random code in any case, it helped me a lot getting started on this feature :)

For what it's worth, I'm pretty sure the minimal case is just the first 12 points in that array I posted. Seemed like the algorithm shorts out after that. I've mostly ripped out this code in place of MIConvexHull so I can't test it properly anymore.

**Comment by OskarSigvardsson** [comment]
I had a think on it overnight, and I figured out what the problem is. The way the algorithm works is that it starts with a "seed hull", which is then grown to encompass all the points. I select the initial tetrahedron by just picking the first four points in the supplied list of points and blithely assumes that those make up a valid tetrahedron (i.e. are not coplanar or collinear). This worked for my use-case because all my points were random, but it obviously doesn't work in general. There's even a comment on it in the code at the top of `GenerateInitialHull`. Now that I know what the problem is, the fix should be fairly straightforward, just select the inital hull in a smarter way.  

I'll let you know if I decide to take time out to fix it. It would be nice to clean this thing up a little bit so other people can use it.

**Comment by OskarSigvardsson** [comment]
@SlimeQ I took some time today and fixed it. It was what I thought, and the fix was straight-forward. Even if you do decide to got with the other library, I'd appreciate it if you could test my update out to confirm that the bug's been fixed. 

The original problem in this issue, that it doesn't work for planes, I'm not going to fix. If you have less than 4 points, or your points are all coincident, collinear or coplanar, then the 3d convex hull isn't really defined. I made the class explicitly throw in those cases.
