### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by jkant** [OskarSigvardsson/unity-quickhull#8]
Hello! First of all I want to thank you for this code snippet which I have found very useful. I just wanted to report an error I have been running into when attempting to generate a hull for a specific mesh - 

GK.ConvexHullCalculator.FindHorizon (System.Collections.Generic.List`1[T] points, UnityEngine.Vector3 point, System.Int32 fi, GK.ConvexHullCalculator+Face face) (at ConvexHullCalculator.cs:666)

I think this may be related to points being too close to one another, so I was messing around with the epsilon setting. But decreasing the epsilon value actually led to many more errors of the same kind, which I was not expecting.

**Comment by OskarSigvardsson** [comment]
Hello! I'm not really actively developing this repository anymore, but if I have time I might look into it. 

Small points could definitely cause issues, and indeed one of my suggestions was going to be to mess with the epsilon setting. Another thing you could try is just scaling up your points. I don't know how small they are, but if you multiply them so that they're around the 1.0 (you know, in that magnitude), run the algorithm, then unscale the resulting shape back, it might work. 

It could also have something do to with your points being "highly planar" or something like that? Not sure. Let me know if you figure out a solution for it.

**Comment by jkant** [comment]
I've been going with your "scale up then scale down" solution so far and it's working fine. Thanks again for this snippet, I've made gotten plenty of use out of it for many years now!

**Comment by OskarSigvardsson** [comment]
Glad to hear it worked out! I'm curious, have you used this in anything you've released or sold? Not for any licensing or credit or anything like that (I don't care, I'm just happy these things are helpful, they're MIT licensed for a reason), but I've always been curious if one of my libraries have wound up in a sold game. I suspect they have, but nobody has actually told me 🙂

**Comment by jkant** [comment]
Your code has been shipped! I work with Tender Claws, and used your convex hull code in Stranger Things VR and VVR 2. Sometimes we will use it to create a 3D hull of the play space to keep certain objects from entering it. But most commonly we use the 3D hull as an input for a custom tool that will spit out a simplified 2D hull, which we use for special effects like imposter rendering.

**Comment by OskarSigvardsson** [comment]
@jkant Sorry for the late response, but I missed your message when it come in. 

That's really lovely to hear, you made my day :) Hope you find more uses for it in the future!
